name: eShopOnWeb - Push Docker Image to GitHub Packages

on: workflow_dispatch

jobs:
  docker:
    env:
      REGISTRY: ghcr.io
      DOCKER_BUILD_SUMMARY: true
      DOCKER_BUILD_RECORD_UPLOAD: true
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: string
      name: Lowercase repositoryname
      uses: Entepotenz/change-string-case-action-min-dependencies@v1.2.0
      with:
        string: ${{ github.repository }}
    - uses: docker/build-push-action@v6
      with:
        file: ${{github.workspace}}/src/Web/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest
