name: eShopOnWeb - Push Docker Image to Git Artifacts

on: workflow_dispatch

jobs:
  docker:
    env:
      REGISTRY: ghcr.io
      DOCKER_BUILD_SUMMARY: true
      DOCKER_BUILD_RECORD_UPLOAD: true
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        file: ${{github.workspace}}/dockerFile/Dockerfile
        push: true
        tags: eshoponweb/web:latest
